/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as OnboardingStep5RouteImport } from './routes/onboarding/step5'
import { Route as OnboardingStep4RouteImport } from './routes/onboarding/step4'
import { Route as OnboardingStep3RouteImport } from './routes/onboarding/step3'
import { Route as OnboardingStep2RouteImport } from './routes/onboarding/step2'
import { Route as OnboardingStep1RouteImport } from './routes/onboarding/step1'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding/complete'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const OnboardingStep5Route = OnboardingStep5RouteImport.update({
  id: '/step5',
  path: '/step5',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep4Route = OnboardingStep4RouteImport.update({
  id: '/step4',
  path: '/step4',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep3Route = OnboardingStep3RouteImport.update({
  id: '/step3',
  path: '/step3',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep2Route = OnboardingStep2RouteImport.update({
  id: '/step2',
  path: '/step2',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep1Route = OnboardingStep1RouteImport.update({
  id: '/step1',
  path: '/step1',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => OnboardingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/step1': typeof OnboardingStep1Route
  '/onboarding/step2': typeof OnboardingStep2Route
  '/onboarding/step3': typeof OnboardingStep3Route
  '/onboarding/step4': typeof OnboardingStep4Route
  '/onboarding/step5': typeof OnboardingStep5Route
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/step1': typeof OnboardingStep1Route
  '/onboarding/step2': typeof OnboardingStep2Route
  '/onboarding/step3': typeof OnboardingStep3Route
  '/onboarding/step4': typeof OnboardingStep4Route
  '/onboarding/step5': typeof OnboardingStep5Route
  '/': typeof AuthenticatedIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/step1': typeof OnboardingStep1Route
  '/onboarding/step2': typeof OnboardingStep2Route
  '/onboarding/step3': typeof OnboardingStep3Route
  '/onboarding/step4': typeof OnboardingStep4Route
  '/onboarding/step5': typeof OnboardingStep5Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/onboarding/complete'
    | '/onboarding/step1'
    | '/onboarding/step2'
    | '/onboarding/step3'
    | '/onboarding/step4'
    | '/onboarding/step5'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/logout'
    | '/onboarding/complete'
    | '/onboarding/step1'
    | '/onboarding/step2'
    | '/onboarding/step3'
    | '/onboarding/step4'
    | '/onboarding/step5'
    | '/'
    | '/onboarding'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/onboarding/complete'
    | '/onboarding/step1'
    | '/onboarding/step2'
    | '/onboarding/step3'
    | '/onboarding/step4'
    | '/onboarding/step5'
    | '/_authenticated/'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/onboarding/step5': {
      id: '/onboarding/step5'
      path: '/step5'
      fullPath: '/onboarding/step5'
      preLoaderRoute: typeof OnboardingStep5RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step4': {
      id: '/onboarding/step4'
      path: '/step4'
      fullPath: '/onboarding/step4'
      preLoaderRoute: typeof OnboardingStep4RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step3': {
      id: '/onboarding/step3'
      path: '/step3'
      fullPath: '/onboarding/step3'
      preLoaderRoute: typeof OnboardingStep3RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step2': {
      id: '/onboarding/step2'
      path: '/step2'
      fullPath: '/onboarding/step2'
      preLoaderRoute: typeof OnboardingStep2RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step1': {
      id: '/onboarding/step1'
      path: '/step1'
      fullPath: '/onboarding/step1'
      preLoaderRoute: typeof OnboardingStep1RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof OnboardingRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingStep1Route: typeof OnboardingStep1Route
  OnboardingStep2Route: typeof OnboardingStep2Route
  OnboardingStep3Route: typeof OnboardingStep3Route
  OnboardingStep4Route: typeof OnboardingStep4Route
  OnboardingStep5Route: typeof OnboardingStep5Route
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingStep1Route: OnboardingStep1Route,
  OnboardingStep2Route: OnboardingStep2Route,
  OnboardingStep3Route: OnboardingStep3Route,
  OnboardingStep4Route: OnboardingStep4Route,
  OnboardingStep5Route: OnboardingStep5Route,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
