[program:nginx]
autorestart=true
startretries=10
command=/srv/system/run_nginx.sh
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile_maxbytes=0

[program:app_server]
autorestart=true
startretries=10
command=/srv/system/run_app_server.sh
startsecs=5
environment=PYTHONPATH=/srv
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile_maxbytes=0

[program:vite]
autorestart=true
startretries=10
command=/srv/system/run_vite_server.sh
startsecs=0
directory=/srv/ui
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile_maxbytes=0

[program:watch_photos]
autorestart=true
startretries=10
command=bash -c "nice -n 16 python /srv/photonix/manage.py watch_photos"
startsecs=10
environment=PYTHONPATH=/srv
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile_maxbytes=0

[program:raw_scheduler]
autorestart=true
startretries=10
command=bash -c "sleep 5 && nice -n 17 python /srv/photonix/manage.py raw_scheduler"
startsecs=15
environment=PYTHONPATH=/srv
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile_maxbytes=0

[program:raw_processor]
autorestart=true
startretries=10
command=bash -c "sleep 6 && nice -n 17 python /srv/photonix/manage.py raw_processor"
startsecs=16
environment=PYTHONPATH=/srv
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile_maxbytes=0

[program:thumbnail_scheduler]
autorestart=true
startretries=10
command=bash -c "sleep 7 && nice -n 17 python /srv/photonix/manage.py thumbnail_processor"
startsecs=17
environment=PYTHONPATH=/srv
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile_maxbytes=0

[program:rescan_photos_periodically]
autorestart=true
startretries=10
command=bash -c "sleep 15 && nice -n 16 python /srv/photonix/manage.py rescan_photos_periodically"
startsecs=25
environment=PYTHONPATH=/srv
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile_maxbytes=0
