# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 21:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('manufacturer', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('earliest_photo', models.DateTimeField()),
                ('latest_photo', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('size_x', models.FloatField()),
                ('size_y', models.FloatField()),
                ('source', models.CharField(choices=[('H', 'Human'), ('A', 'AI')], max_length=1)),
                ('confidence', models.FloatField()),
                ('verified', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('manufacturer', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('earliest_photo', models.DateTimeField()),
                ('latest_photo', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'lenses',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('taken_at', models.DateTimeField(null=True)),
                ('taken_by', models.CharField(blank=True, max_length=128)),
                ('aperture', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('exposure', models.CharField(blank=True, max_length=8)),
                ('iso_speed', models.PositiveIntegerField(null=True)),
                ('focal_length', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('flash', models.NullBooleanField()),
                ('metering', models.CharField(max_length=32)),
                ('drive_mode', models.CharField(max_length=32)),
                ('shooting_mode', models.CharField(max_length=32)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.Camera')),
                ('lens', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.Lens')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('path', models.CharField(max_length=512)),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('J', 'JPEG'), ('R', 'Raw'), ('P', 'PNG'), ('T', 'TIFF')], max_length=1)),
                ('file_modified_at', models.DateTimeField()),
                ('bytes', models.PositiveIntegerField()),
                ('preferred', models.BooleanField(default=False)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='photos.Photo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('source', models.CharField(choices=[('H', 'Human'), ('A', 'AI')], max_length=1)),
                ('confidence', models.FloatField()),
                ('verified', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_tags', to='photos.Photo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('name', models.CharField(max_length=128)),
                ('source', models.CharField(choices=[('H', 'Human'), ('A', 'AI')], max_length=1)),
                ('category', models.CharField(choices=[('CO', 'Country'), ('RE', 'Region')], max_length=2, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='photos.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='phototag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_tags', to='photos.Tag'),
        ),
        migrations.AddField(
            model_name='face',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='photos.Person'),
        ),
        migrations.AddField(
            model_name='face',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='photos.Photo'),
        ),
    ]
