# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-20 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='last_auto_tagged_locations_at',
            new_name='last_tagged_locations_at',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='last_auto_tagged_locations_version',
            new_name='last_tagged_locations_version',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='last_auto_tagged_features_at',
            new_name='last_tagged_objects_at',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='last_auto_tagged_features_version',
            new_name='last_tagged_objects_version',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='last_auto_tagged_people_at',
            new_name='last_tagged_people_at',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='last_auto_tagged_people_version',
            new_name='last_tagged_people_version',
        ),
        migrations.AddField(
            model_name='photo',
            name='last_tagged_colors_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='last_tagged_colors_version',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='last_tagged_styles_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='last_tagged_styles_version',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='phototag',
            name='position_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phototag',
            name='position_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phototag',
            name='size_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phototag',
            name='size_y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('L', 'Location'), ('O', 'Object'), ('P', 'Person'), ('C', 'Color'), ('S', 'Style')], max_length=1, null=True),
        ),
    ]
