# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 20:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedConfig',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('val', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
