services:
  init:
    image: busybox:latest
    volumes:
      - ./data:/data
    command: >
      /bin/sh -c "mkdir -p /data/photos /data/raw-photos-processed /data/cache /data/models &&
                  chown -R 2000:2000 /data/photos /data/raw-photos-processed /data/cache /data/models"

  postgres:
    container_name: photonix-postgres
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: photonix
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/db:/var/lib/postgresql/data

  redis:
    container_name: photonix-redis
    image: redis:8-alpine

  photonix:
    user: "2000:2000"
    container_name: photonix
    image: photonixapp/photonix:latest
    ports:
      - '8888:80'
    environment:
      ENV: prd
      POSTGRES_HOST: postgres
      POSTGRES_DB: photonix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      REDIS_HOST: redis
      ALLOWED_HOSTS: '*'
      # More configuration options here: https://photonix.org/docs/configuration/
    volumes:
      - ./data/photos:/data/photos
      - ./data/raw-photos-processed:/data/raw-photos-processed
      - ./data/cache:/data/cache
      - ./data/models:/data/models
    links:
      - postgres
      - redis
    depends_on:
      - init
