FROM python:3.8.6-slim-buster

RUN apt-get update && \
    apt-get install -y \
        build-essential \
        curl \
        dcraw \
        git \
        gnupg \
        libimage-exiftool-perl \
        libjpeg-dev \
        libpq-dev \
        libtiff5-dev \
        netcat \
        nginx-light \
        supervisor \
    && \
        apt-get clean && \
            rm -rf /var/lib/apt/lists/* \
                   /tmp/* \
                   /var/tmp/*

# Install Node & Yarn
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && \
    apt-get install -y nodejs yarn && \
         apt-get clean && \
            rm -rf /var/lib/apt/lists/* \
                   /tmp/* \
                   /var/tmp/*

# Install Python dependencies
WORKDIR /srv

COPY docker/pip.conf /etc/pip.conf
COPY docker/.pypirc /root/.pypirc
RUN pip install --upgrade pip
RUN pip install --no-cache-dir pypi-uploader==1.1.0

COPY requirements.txt /srv/requirements.txt
COPY docker/install_and_upload_python_packages.py /root/install_and_upload_python_packages.py
ENV PYTHONUNBUFFERED=1
ARG PYPI_UPLOAD_USERNAME
ARG PYPI_UPLOAD_PASSWORD
RUN if [ "${PYPI_UPLOAD_USERNAME}" = "" ] ; \
     then python /root/install_and_upload_python_packages.py ; \
     else python /root/install_and_upload_python_packages.py -u ${PYPI_UPLOAD_USERNAME} -p ${PYPI_UPLOAD_PASSWORD} ; \
    fi

# Install NPM dependencies
COPY ui/package.json /srv/ui/package.json
COPY ui/yarn.lock /srv/ui/yarn.lock
ENV NODE_ENV=development
RUN cd /srv/ui && yarn install

# Copy over the code
COPY photonix /srv/photonix
COPY test.py /srv/test.py
COPY tests /srv/tests
COPY ui/public /srv/ui/public
COPY ui/src /srv/ui/src

# Copy system config and init scripts
COPY system /srv/system
COPY system/supervisord.conf /etc/supervisord.conf

ENV PYTHONPATH /srv

CMD ./system/run.sh

EXPOSE 80
