# Generated by Django 3.0.7 on 2020-12-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_config_persional_info',
            field=models.BooleanField(default=False, help_text='true if user has registered persional info?'),
        ),
    ]
