# Generated by Django 3.0.3 on 2020-03-19 13:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('type', models.CharField(choices=[('St', 'Store'), ('Im', 'Import only'), ('Th', 'Thumbnails')], help_text='What type of path this is', max_length=2)),
                ('backend_type', models.CharField(choices=[('Lo', 'Local filesystem'), ('S3', 'S3-compatible block storage')], help_text='What type of storage to use for imported photos', max_length=2)),
                ('path', models.CharField(blank=True, help_text='Path for storing photos - local path or bucket name', max_length=128, null=True)),
                ('url', models.CharField(blank=True, help_text='If a public-facing URL is available to access block storage, client will use this to download photos', max_length=128, null=True)),
                ('delete_after_import', models.BooleanField(default=False, help_text='Remove the photo from import_path after import succeeded?')),
                ('watch_for_changes', models.BooleanField(default=False, help_text='Watch import_path for local filesystem changes?')),
                ('s3_access_key_id', models.CharField(help_text='AWS S3 (or compatible) access key ID', max_length=20)),
                ('s3_secret_key', models.CharField(help_text='AWS S3 (or compatible) secret key', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='library',
            name='backend_type',
        ),
        migrations.RemoveField(
            model_name='library',
            name='base_path',
        ),
        migrations.RemoveField(
            model_name='library',
            name='base_thumbnail_path',
        ),
        migrations.RemoveField(
            model_name='library',
            name='base_thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='library',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='library',
            name='delete_after_import',
        ),
        migrations.RemoveField(
            model_name='library',
            name='import_path',
        ),
        migrations.RemoveField(
            model_name='library',
            name='watch_files',
        ),
        migrations.AddField(
            model_name='library',
            name='setup_stage_completed',
            field=models.CharField(blank=True, choices=[('St', 'Storage backend configured'), ('Im', 'Photo importing configured'), ('Th', 'Thumbnailing storage configured')], help_text='Where the user got to during onboarding setup', max_length=2, null=True),
        ),
    ]
