# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-24 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('type', models.CharField(db_index=True, max_length=128)),
                ('subject_id', models.UUIDField()),
                ('status', models.CharField(choices=[('L', 'Location'), ('O', 'Object'), ('F', 'Face'), ('C', 'Color'), ('S', 'Style')], db_index=True, default='P', max_length=1)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='face',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='classifier_color_completed_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='classifier_color_queued_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='classifier_color_version',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='classifier_location_completed_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='classifier_location_queued_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='classifier_location_version',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='classifier_object_completed_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='classifier_object_queued_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='classifier_object_version',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='classifier_person_completed_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='classifier_person_queued_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='classifier_person_version',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='classifier_style_completed_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='classifier_style_queued_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='classifier_style_version',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='last_thumbnailed_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='last_thumbnailed_version',
        ),
        migrations.RemoveField(
            model_name='phototag',
            name='face',
        ),
        migrations.AddField(
            model_name='photo',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('L', 'Location'), ('O', 'Object'), ('F', 'Face'), ('C', 'Color'), ('S', 'Style')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Face',
        ),
    ]
