# Generated by Django 3.0.7 on 2020-12-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_crt_star_rating_fld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='star_rating',
            field=models.PositiveIntegerField(blank=True, help_text='assign rating to photo', null=True, verbose_name='Rating'),
        ),
    ]
