# Generated by Django 3.0.3 on 2020-03-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20200319_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryuser',
            options={},
        ),
        migrations.AlterField(
            model_name='librarypath',
            name='path',
            field=models.CharField(default='Lo', help_text='Path for storing photos - local path or bucket name', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='librarypath',
            name='s3_access_key_id',
            field=models.CharField(blank=True, help_text='AWS S3 (or compatible) access key ID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='librarypath',
            name='s3_secret_key',
            field=models.CharField(blank=True, help_text='AWS S3 (or compatible) secret key', max_length=40, null=True),
        ),
    ]
