# Generated by Django 3.0.7 on 2021-01-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20201229_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='is_active',
            field=models.BooleanField(default=False, help_text='To check is this users active library?', verbose_name='Active'),
        ),
    ]
