# Generated by Django 3.0.7 on 2021-01-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20201229_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['ordering', 'name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='ordering',
            field=models.FloatField(null=True),
        ),
    ]
