# Generated by Django 3.0.3 on 2020-03-19 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20200319_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarypath',
            name='library',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='photos.Library'),
            preserve_default=False,
        ),
    ]
