# Generated by Django 3.0.7 on 2021-01-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20201229_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototag',
            name='extra_data',
            field=models.TextField(null=True),
        ),
    ]
