# Generated by Django 3.0.7 on 2021-01-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_add_Genric_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototag',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_tags', to='photos.Photo'),
        ),
    ]
