# Generated by Django 3.0.7 on 2021-01-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_crtIsActiveFld'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='is_active',
        ),
    ]
