# Generated by Django 3.0.7 on 2021-02-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20210130_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['ordering', 'name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='ordering',
            field=models.FloatField(null=True),
        ),
    ]
