# Generated by Django 3.0.7 on 2021-04-06 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20210321_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_library', to='photos.Library'),
        ),
    ]
