# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20190306_1827'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='camera',
            unique_together=set([('make', 'model')]),
        ),
    ]
