# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-19 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20190507_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photofile',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photofile',
            name='width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
