# Generated by Django 3.0.14 on 2021-05-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_add_library_ForeignKey'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototag',
            name='extra_data',
            field=models.TextField(null=True),
        ),
    ]
