# Generated by Django 3.0.7 on 2021-04-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_add_library_ForeignKey'),
    ]

    operations = [
        migrations.AddField(
            model_name='photofile',
            name='rotate',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
