# Generated by Django 3.0.14 on 2021-06-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20210604_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='photofile',
            name='rotation',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
