# Generated by Django 3.2.3 on 2021-05-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20210529_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='flash',
            field=models.BooleanField(null=True),
        ),
    ]
