# Generated by Django 3.2.3 on 2021-07-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20210617_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photofile',
            name='raw_external_params',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='photofile',
            name='raw_external_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
