# Generated by Django 3.2.3 on 2021-07-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_auto_20210710_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('L', 'Location'), ('O', 'Object'), ('F', 'Face'), ('C', 'Color'), ('S', 'Style'), ('G', 'Generic'), ('E', 'Event'), ('A', 'Album')], db_index=True, max_length=1, null=True),
        ),
    ]
