# Generated by Django 3.2.3 on 2021-07-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_alter_tag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
