# Generated by Django 3.2.12 on 2022-03-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_crt_photo_delete_fld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototag',
            name='source',
            field=models.CharField(choices=[('C', 'Computer'), ('H', 'Human')], db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='source',
            field=models.CharField(choices=[('C', 'Computer'), ('H', 'Human')], db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('A', 'Album'), ('C', 'Color'), ('E', 'Event'), ('F', 'Face'), ('G', 'Generic'), ('L', 'Location'), ('O', 'Object'), ('S', 'Style')], db_index=True, max_length=1, null=True),
        ),
    ]
