# Generated by Django 3.2.12 on 2022-03-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_auto_20220312_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='photofile',
            name='rotation',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
