# Generated by Django 3.2.12 on 2026-01-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_photofile_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='memory_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Started'), ('C', 'Completed'), ('F', 'Failed'), ('M', 'Memory Wait')], db_index=True, default='P', max_length=1),
        ),
    ]
