# Generated by Django 3.2.12 on 2026-01-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_add_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='photofile',
            name='exif_rotation',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.RenameField(
            model_name='photofile',
            old_name='rotation',
            new_name='user_rotation',
        ),
    ]
