# Generated by Django 4.2.28 on 2026-02-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0018_add_task_delayed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Started'), ('C', 'Completed'), ('F', 'Failed'), ('M', 'Memory Wait'), ('D', 'Delayed')], db_index=True, default='P', max_length=1),
        ),
    ]
