# Generated by Django 6.0.4 on 2026-07-19 08:01

from django.db import migrations, models


def enable_event_for_existing_libraries(apps, schema_editor):
    # Event tagging had no toggle before this field existed - it always ran.
    # Existing libraries must keep that behaviour; only newly created
    # libraries start disabled (and opt in during onboarding like the other
    # classifiers).
    Library = apps.get_model('photos', 'Library')
    Library.objects.all().update(classification_event_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0019_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='classification_event_enabled',
            field=models.BooleanField(default=False, help_text='Run event detection on photos?'),
        ),
        migrations.RunPython(
            enable_event_for_existing_libraries,
            migrations.RunPython.noop,
        ),
    ]
