# Generated by Django 6.0.4 on 2026-07-19 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0020_library_classification_event_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='classification_clip_enabled',
            field=models.BooleanField(default=False, help_text='Run CLIP semantic embedding on photos?'),
        ),
        migrations.CreateModel(
            name='PhotoEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('type', models.CharField(choices=[('C', 'CLIP')], db_index=True, help_text='Which model produced the embedding, e.g. CLIP', max_length=16)),
                ('model_version', models.PositiveIntegerField(default=0, help_text='Version number of the model that produced this embedding (YYYYMMDD)')),
                ('embedding', models.BinaryField(help_text='Raw little-endian float32 bytes of the embedding vector')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='photos.photo')),
            ],
            options={
                'unique_together': {('photo', 'type')},
            },
        ),
    ]
