# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-11 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('make', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('earliest_photo', models.DateTimeField()),
                ('latest_photo', models.DateTimeField()),
            ],
            options={
                'ordering': ['make', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('size_x', models.FloatField()),
                ('size_y', models.FloatField()),
                ('source', models.CharField(choices=[('H', 'Human'), ('C', 'Computer')], max_length=1)),
                ('confidence', models.FloatField()),
                ('verified', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('name', models.CharField(max_length=128)),
                ('earliest_photo', models.DateTimeField()),
                ('latest_photo', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'lenses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('taken_at', models.DateTimeField(null=True)),
                ('taken_by', models.CharField(blank=True, max_length=128, null=True)),
                ('aperture', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('exposure', models.CharField(blank=True, max_length=8, null=True)),
                ('iso_speed', models.PositiveIntegerField(null=True)),
                ('focal_length', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('flash', models.NullBooleanField()),
                ('metering_mode', models.CharField(max_length=32, null=True)),
                ('drive_mode', models.CharField(max_length=32, null=True)),
                ('shooting_mode', models.CharField(max_length=32, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('altitude', models.DecimalField(decimal_places=1, max_digits=6, null=True)),
                ('last_thumbnailed_version', models.PositiveIntegerField(null=True)),
                ('last_thumbnailed_at', models.DateTimeField(null=True)),
                ('classifier_color_version', models.PositiveIntegerField(null=True)),
                ('classifier_color_queued_at', models.DateTimeField(null=True)),
                ('classifier_color_completed_at', models.DateTimeField(null=True)),
                ('classifier_location_version', models.PositiveIntegerField(null=True)),
                ('classifier_location_queued_at', models.DateTimeField(null=True)),
                ('classifier_location_completed_at', models.DateTimeField(null=True)),
                ('classifier_object_version', models.PositiveIntegerField(null=True)),
                ('classifier_object_queued_at', models.DateTimeField(null=True)),
                ('classifier_object_completed_at', models.DateTimeField(null=True)),
                ('classifier_person_version', models.PositiveIntegerField(null=True)),
                ('classifier_person_queued_at', models.DateTimeField(null=True)),
                ('classifier_person_completed_at', models.DateTimeField(null=True)),
                ('classifier_style_version', models.PositiveIntegerField(null=True)),
                ('classifier_style_queued_at', models.DateTimeField(null=True)),
                ('classifier_style_completed_at', models.DateTimeField(null=True)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.Camera')),
                ('lens', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.Lens')),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('path', models.CharField(max_length=512)),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('mimetype', models.CharField(blank=True, max_length=32)),
                ('file_modified_at', models.DateTimeField()),
                ('bytes', models.PositiveIntegerField()),
                ('preferred', models.BooleanField(default=False)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='photos.Photo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('source', models.CharField(choices=[('H', 'Human'), ('C', 'Computer')], max_length=1)),
                ('model_version', models.PositiveIntegerField(null=True)),
                ('confidence', models.FloatField()),
                ('significance', models.FloatField(null=True)),
                ('verified', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('position_x', models.FloatField(null=True)),
                ('position_y', models.FloatField(null=True)),
                ('size_x', models.FloatField(null=True)),
                ('size_y', models.FloatField(null=True)),
                ('face', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_tags', to='photos.Face')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_tags', to='photos.Photo')),
            ],
            options={
                'ordering': ['-significance'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('L', 'Location'), ('O', 'Object'), ('P', 'Person'), ('C', 'Color'), ('S', 'Style')], max_length=1, null=True)),
                ('source', models.CharField(choices=[('H', 'Human'), ('C', 'Computer')], max_length=1)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='photos.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='phototag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_tags', to='photos.Tag'),
        ),
        migrations.AddField(
            model_name='face',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='photos.Photo'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('name', 'type', 'source')]),
        ),
    ]
