# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-14 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20171220_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='last_tagged_colors_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='last_tagged_colors_version',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='last_tagged_locations_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='last_tagged_locations_version',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='last_tagged_objects_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='last_tagged_objects_version',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='last_tagged_people_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='last_tagged_people_version',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='last_tagged_styles_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='last_tagged_styles_version',
        ),
        migrations.AddField(
            model_name='photo',
            name='classifier_color_completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='classifier_color_queued_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='classifier_color_version',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='classifier_location_completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='classifier_location_queued_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='classifier_location_version',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='classifier_object_completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='classifier_object_queued_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='classifier_object_version',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='classifier_person_completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='classifier_person_queued_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='classifier_person_version',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='classifier_style_completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='classifier_style_queued_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='classifier_style_version',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
