# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20180714_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['make', 'model']},
        ),
        migrations.AlterModelOptions(
            name='lens',
            options={'ordering': ['name'], 'verbose_name_plural': 'lenses'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['taken_at'], 'verbose_name_plural': 'lenses'},
        ),
    ]
