# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20190225_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='photofile',
            name='raw_external_params',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='photofile',
            name='raw_external_version',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='photofile',
            name='raw_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photofile',
            name='raw_version',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photofile',
            name='mimetype',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
