# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20190305_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photofile',
            name='height',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photofile',
            name='width',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
