# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20181203_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototag',
            name='model_version',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
