# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_phototag_model_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='classifier_color_version',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='classifier_location_version',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='classifier_object_version',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='classifier_person_version',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='classifier_style_version',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='last_thumbnailed_version',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
