# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-29 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_phototag_significance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-taken_at']},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('name', 'type', 'source')]),
        ),
    ]
