# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20181229_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phototag',
            options={'ordering': ['-significance']},
        ),
        migrations.AddField(
            model_name='photo',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
