# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_auto_20190110_2318'),
    ]

    operations = [
    ]
